version: "3.7"
{%- if cookiecutter.with_kafka=="no" -%}
services:
  datascience:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JUPYTER_TOKEN={{ cookiecutter.pass }}
      - JULIA_VERSION={{ cookiecutter.julia_version }}
    volumes:
      - ./{{ cookiecutter.work_directory }}:/home/jovyan/{{cookiecutter.work_directory}}
    ports:
      - 8888:8888
      - 4040:4040
      - 5050:5050
    container_name: rta
{%- endif -%}
{%- if cookiecutter.with_kafka=="yes" -%}
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.3.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  datascience:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - JUPYTER_TOKEN={{ cookiecutter.pass }}
      - JULIA_VERSION={{ cookiecutter.julia_version }}
    volumes:
      - ./{{ cookiecutter.work_directory }}:/home/jovyan/{{cookiecutter.work_directory}}
    ports:
      - 8888:8888
      - 4040:4040
      - 5050:5050
    container_name: rta
    depends_on:
      - broker
{%- endif -%}
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
